export const demo_profile: { id: number; attributes: any }[] = [
    {id: 1, attributes: { name: "藤貫 哲生",age: "20", gender: "男", artist1:"PEOPLE1", motivation1:"🔥🔥🔥🔥🔥",artist2:"Vaundy", motivation2:"🔥🔥🔥🔥🔥",artist3:"TOOBOE", motivation3:"🔥🔥🔥🔥",bio:"一緒にはしゃぎたいです！よろしくお願いします", ng:"冷笑" } },
    {id: 2, attributes: { name: "太郎",age: "24", gender: "男", artist1:"Ms.GREEN APPLE", motivation1:"🔥🔥",artist2:"", motivation2:"",artist3:"", motivation3:"",bio:"ライブ行ったことないから教えて欲しい", ng:"誹謗中傷" } },
    {id: 3, attributes: { name: "花子",age: "19", gender: "女", artist1:"あいみょん", motivation1:"🔥🔥🔥🔥",artist2:"米津玄師", motivation2:"🔥🔥🔥",artist3:"", motivation3:"",bio:"ゆったりと参加したいです", ng:"" } },
    {id: 4, attributes: { name: "ねね",age: "25", gender: "女", artist1:"マカロニえんぴつ", motivation1:"🔥🔥🔥🔥🔥",artist2:"go!go!vanillas", motivation2:"🔥🔥🔥🔥🔥",artist3:"サカナクション", motivation3:"🔥🔥🔥",bio:"フェス仲間探してます", ng:"ダイブ" } },
    {id: 5, attributes: { name: "健太",age: "22", gender: "男", artist1:"back number", motivation1:"🔥🔥🔥🔥🔥",artist2:"Saucy Dog", motivation2:"🔥🔥🔥🔥",artist3:"", motivation3:"",bio:"バラード系が好きです。一緒に聴きませんか？", ng:"ライブ中の過度な撮影" } },
    {id: 6, attributes: { name: "由美",age: "28", gender: "女", artist1:"YOASOBI", motivation1:"🔥🔥🔥🔥🔥",artist2:"Ado", motivation2:"🔥🔥🔥🔥🔥",artist3:"ずっと真夜中でいいのに。", motivation3:"🔥🔥🔥🔥",bio:"ボカロ系が好きです！ノリのいい人と行きたい！", ng:"喫煙" } },
    {id: 7, attributes: { name: "大輝",age: "21", gender: "男", artist1:"ONE OK ROCK", motivation1:"🔥🔥🔥🔥🔥",artist2:"[Alexandros]", motivation2:"🔥🔥🔥🔥🔥",artist3:"SUPER BEAVER", motivation3:"🔥🔥🔥",bio:"ロックフェス専門です。体力には自信あります！", ng:"途中退場" } },
    {id: 8, attributes: { name: "さくら",age: "20", gender: "女", artist1:"back number", motivation1:"🔥🔥🔥🔥",artist2:"", motivation2:"",artist3:"", motivation3:"",bio:"初めてなので色々教えてください。", ng:"" } },
    {id: 9, attributes: { name: "拓也",age: "26", gender: "男", artist1:"Creepy Nuts", motivation1:"🔥🔥🔥🔥🔥",artist2:"BUMP OF CHICKEN", motivation2:"🔥🔥🔥",artist3:"", motivation3:"",bio:"ヒップホップもロックも好きです。気軽に話しましょう。", ng:"ナンパ目的" } },
    {id: 10, attributes: { name: "美咲",age: "23", gender: "女", artist1:"aiko", motivation1:"🔥🔥🔥🔥🔥",artist2:"緑黄色社会", motivation2:"🔥🔥🔥🔥",artist3:"Perfume", motivation3:"🔥🔥🔥",bio:"女性の友達募集中です！", ng:"男性のみのグループ" } },
    {id: 11, attributes: { name: "翔太",age: "18", gender: "男", artist1:"RADWIMPS", motivation1:"🔥🔥🔥🔥",artist2:"", motivation2:"",artist3:"", motivation3:"",bio:"ライブ初心者です。よろしくお願いします！", ng:"割り込み" } },
    {id: 12, attributes: { name: "葵",age: "27", gender: "女", artist1:"Official髭男dism", motivation1:"🔥🔥🔥🔥🔥",artist2:"King Gnu", motivation2:"🔥🔥🔥🔥🔥",artist3:"", motivation3:"",bio:"フェスで美味しいもの食べるのも好きです！", ng:"" } },
    {id: 13, attributes: { name: "蓮",age: "29", gender: "男", artist1:"SEKAI NO OWARI", motivation1:"🔥🔥🔥",artist2:"Vaundy", motivation2:"🔥🔥🔥🔥",artist3:"", motivation3:"",bio:"世界観が独特なアーティストが好きです。", ng:"騒ぎすぎる人" } },
    {id: 14, attributes: { name: "陽菜",age: "22", gender: "女", artist1:"Saucy Dog", motivation1:"🔥🔥🔥🔥🔥",artist2:"My Hair is Bad", motivation2:"🔥🔥🔥",artist3:"クリープハイプ", motivation3:"🔥🔥🔥",bio:"邦ロック好きと繋がりたい！", ng:"しつこい連絡" } }
    //{id: 1, attributes: { name: "",age: "", gender: "", artist1:"", motivation1:"",artist2:"", motivation2:"",artist3:"", motivation3:"",bio:"", ng:"" } }
];